name: build

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup bazel
        run: |
          sudo curl --create-dirs -SLo /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.8.0/bazelisk-linux-amd64
          sudo chmod +x /usr/local/bin/bazel

      - name: configure
        run: |
          cmake -H. -Bbuild

      - name: compile
        run: |
          cmake --build build -- -j$(nproc)
