name: build

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aceforeverd/hybridsql-base:0.0.8
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: setup bazel
        run: |
          curl --create-dirs -SLo /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.8.0/bazelisk-linux-amd64
          chmod +x /usr/local/bin/bazel

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.20.x'

      - name: download thirdparty
        run: |
          curl -SLo thirdparty.tar.gz https://github.com/aceforeverd/hybridsql-asserts/releases/download/v0.2.0-beta2/thirdparty-2021-05-13.tar.gz
          tar xzf thirdparty.tar.gz
          mv thirdparty-*/ thirdparty/

      - name: configure
        env:
          DEPS_BUILD_DIR: /__w/zetasql-sample/zetasql-sample/thirdparty
        run: |
          cmake -H. -Bbuild

      - name: compile
        env:
          DEPS_BUILD_DIR: /__w/zetasql-sample/zetasql-sample/thirdparty
        run: |
          cmake --build build -- -j$(nproc)

      - name: test
        run: |
          ./build/parse_tree_test
